site_name: BOSWatch3 Core
site_author: Bastian Schroll & BW3 Dev team

repo_url: https://github.com/BOSWatch/BW3-Core
edit_uri: edit/develop/docu/docs/

nav:
  # - BW3: index.md
  - Quick Start Guide:
#      - Installation: tbd.md
      - Konfiguration: config.md
#      - BOSWatch nutzen: tbd.md
#      - BOSWatch als Service: tbd.md
#  - Informationen:
#      - Server/Cient Prinzip: tbd.md
#      - Broadcast Funktion: tbd.md
#      - Modul/Plugin Konzept: tbd.md
#      - Routing Mechanismus: tbd.md
  - Module:
      - Mode Filter: modul/mode_filter.md
#  - Plugins: tbd.md
  - Entwickler:
    - Eigenes Modul/Plugin: develop/ModulPlugin.md
    - BOSWatch Packet Format: develop/packet.md
    - BW3 Source Docu: /api/html/index.html
  - Changelog: changelog.md

use_directory_urls: false

theme:
  name: mkdocs
  highlightjs: true
  hljs_style: github


