# -*- coding: utf-8 -*-
#    ____  ____  ______       __      __       __       _____
#   / __ )/ __ \/ ___/ |     / /___ _/ /______/ /_     |__  /
#  / __  / / / /\__ \| | /| / / __ `/ __/ ___/ __ \     /_ <
# / /_/ / /_/ /___/ /| |/ |/ / /_/ / /_/ /__/ / / /   ___/ /
#/_____/\____//____/ |__/|__/\__,_/\__/\___/_/ /_/   /____/
#                German BOS Information Script
#                     by Bastian Schroll

client:
  name: BW3 Client        # name of the BW3 Client instance
  inputSource: stick      # possible is 'stick' or 'audio'
#  useBroadcast: yes       # use broadcast function to find server

# atm only one server possible
server:                  # only used if useBroadcast = no
  name: Server one
  ip:   127.0.0.1
  port: 8080

inputSource:
  stick:
    device: 0
    frequency: 85.000M
    PPMError: 0
    Squelch: 0
    Gain: 100
  audio:                  # not implemented yet

decoder:                  # not implemented yet
  fms: yes
  zvei: yes
  poc512: yes
  poc1200: yes
  poc2400: yes
