# -*- coding: utf-8 -*-
#    ____  ____  ______       __      __       __       _____
#   / __ )/ __ \/ ___/ |     / /___ _/ /______/ /_     |__  /
#  / __  / / / /\__ \| | /| / / __ `/ __/ ___/ __ \     /_ <
# / /_/ / /_/ /___/ /| |/ |/ / /_/ / /_/ /__/ / / /   ___/ /
#/_____/\____//____/ |__/|__/\__,_/\__/\___/_/ /_/   /____/
#                German BOS Information Script
#                     by Bastian Schroll

client:
  name: BW3 Client        # name of the BW3 Client instance
  inputSource: sdr        # name of the input source('sdr' or 'lineIn')
  useBroadcast: no        # use broadcast to find server automatically
  reconnectDelay: 3       # time in seconds to delay reconnect try
  sendTries: 3            # how often should tried to send a packet
  sendDelay: 3            # time in seconds to delay the resend try

server:                   # only used if useBroadcast = no
  ip: 127.0.0.1           # use service name if you are running docker
  port: 8080

inputSource:
  sdr:
    device: 0
    frequency: 85M
    error: 0
    squelch: 1
    gain: 100
    #fir_size: 0
    rtlPath: /usr/local/bin/rtl_fm
  lineIn:
    card: 1
    device: 0

decoder:
  fms: yes
  zvei: yes
  poc512: yes
  poc1200: yes
  poc2400: yes
  Path: /opt/multimon/multimon-ng
  char: DE
