# -*- coding: utf-8 -*-
#    ____  ____  ______       __      __       __       _____
#   / __ )/ __ \/ ___/ |     / /___ _/ /______/ /_     |__  /
#  / __  / / / /\__ \| | /| / / __ `/ __/ ___/ __ \     /_ <
# / /_/ / /_/ /___/ /| |/ |/ / /_/ / /_/ /__/ / / /   ___/ /
#/_____/\____//____/ |__/|__/\__,_/\__/\___/_/ /_/   /____/
#                German BOS Information Script
#                     by Bastian Schroll

server:
  port: 8080
  name: BW3 Server        # name of the BW3 Server instance
  useBroadcast: no        # serve server ip on broadcast request

alarmRouter:
- Alarm_multicast

router:
- name: Alarm_multicast
  route:
  - type: module
    res: filter.regexFilter
    config:
      - name: "valid multicast rics"
        checks:
          - field: ric 
            regex: 210000|210002|210003
  - type: module
    res: filter.doubleFilter
    name: Filter double
    config:
      ignoreTime: 10
      maxEntry: 10
      pocsagFields:
       - ric 
       - subric
  - type: module
    res: multicast
    name: Find the multicast message infos
    config:
      multicastAlarm_textRics: 2100002,210001
      multicastAlarm_ignore_time: 10 
      multicastAlarm_delimiterRic: 2100003
      multicastAlarm_delimiterSubric: 0
