name: build_docs

on:
  push:
    branches:
      - master
      - feature/gh-pages

jobs:

  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build doxygen
      uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: './'
        doxyfile-path: 'docu/doxygen.ini'

    - name: Build mkdocs
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs
        python -m mkdocs build -f docu/mkdocs.yml
    - run: python -m mkdocs gh-deploy --force
