name: build_docs

on:
  push:
    branches:
      - master

jobs:

  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Build doxygen
      uses: mattnotmitt/doxygen-action@v1
      with:
        working-directory: './'
        doxyfile-path: 'docu/doxygen.ini'

    - name: Build mkdocs
      run: |
        python -m pip install --upgrade pip
        pip install mkdocs
        python -m mkdocs build -f docu/mkdocs.yml

    - name: Upload to docs-server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SCP_HOST }}
        port: ${{ secrets.SCP_PORT }}
        username: ${{ secrets.SCP_USERNAME }}
        password: ${{ secrets.SCP_PASSWORD }}
        source: "docu/site/**"
        target: ${{ secrets.SCP_TARGET_PATH }}
        strip_components: 2
