name: build_docs

on:
  push:
    branches:
      #- master
      - develop

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_docs:
    name: Build documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen
        pip install mkdocs
    - name: Build doxygen
      run: doxygen docu/doxygen.ini
    - name: Build MkDocs site
      working-directory: docu
      run: mkdocs build --site-dir site
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./docu/site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_docs
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
