name: Build Docker Image

on:
  push:
    branches: [ master, feature/docker ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag boswatch:$(date +%s)
    - name: docker login
      run: docker login docker.pkg.github.com --username janspeller
    - name: Push the Docker image to Github Packages
      run: docker tag boswatch docker.pkg.github.com/janspeller/BW3-Core/boswatch:latest
