name: Build Docker Image

on:
  push:
    branches:
      - master
      - feature/docker

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image for the Client
      run: docker build . --file Dockerfile --target client --tag docker.pkg.github.com/janspeller/bw3-core/client:latest
    - name: Build the Docker image for the Server
      run: docker build . --file Dockerfile --target server --tag docker.pkg.github.com/janspeller/bw3-core/server:latest
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_PAT }}
    - name: Push the Client Docker image to Github package repository
      run: docker push docker.pkg.github.com/janspeller/bw3-core/client:latest
    - name: Push the Server Docker image to Github package repository
      run: docker push docker.pkg.github.com/janspeller/bw3-core/server:latest
