name: Build Docker Image

on:
  push:
    branches: [ master, feature/docker ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag boswatch:$(date +%s)

