name: BW Docs

on:
  push:
    branches: 
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        mkdir log/
    - name: Build doxygen
      run: echo 'tbd...'
    - name: Build mkDocs
      run: mkdocs build -f docu/mkdocs.yml
    - name: Deploy docs
      run: echo 'tbd...'
